'use client';
import { useId, useState, type CSSProperties } from 'react';
import { sitePath } from '@/lib/site-path';
import { presets, fonts, onColor, contrast, hsl, lessons, type Design } from '@/lib/design-lab';
import { Slider } from '@/components/ui/slider';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';

function Range({label,value,min,max,step=1,unit='',change}:{label:string;value:number;min:number;max:number;step?:number;unit?:string;change:(v:number)=>void}){
 const id=useId();return <div className="dl-range"><div><label id={id}>{label}</label><span>{value}{unit}</span></div><Slider aria-labelledby={id} value={[value]} min={min} max={max} step={step} onValueChange={v=>change(Array.isArray(v)?v[0]:v)}/><input aria-label={`${label} value`} type="number" value={value} min={min} max={max} step={step} onChange={e=>{if(e.target.value!=='')change(Math.min(max,Math.max(min,Number(e.target.value))));}}/></div>;
}
function Choice({label,value,options,change}:{label:string;value:string;options:{value:string;label:string}[];change:(v:string)=>void}){const id=useId();return <div className="dl-field"><label id={id}>{label}</label><Select value={value} onValueChange={v=>v&&change(v)}><SelectTrigger aria-labelledby={id}><SelectValue>{options.find(o=>o.value===value)?.label}</SelectValue></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select></div>;}
function Color({label,value,change}:{label:string;value:string;change:(v:string)=>void}){const [draft,setDraft]=useState(value);const invalid=!/^#[\da-f]{6}$/i.test(draft);return <div className="dl-color"><label>{label}<input aria-label={`${label} picker`} type="color" value={value} onChange={e=>{setDraft(e.target.value);change(e.target.value);}}/></label><input aria-label={`${label} hex`} value={draft} spellCheck={false} maxLength={7} aria-invalid={invalid} onChange={e=>{setDraft(e.target.value);if(/^#[\da-f]{6}$/i.test(e.target.value))change(e.target.value);}}/>{invalid&&<small>Use # and six hexadecimal digits. Preview keeps the last valid color.</small>}</div>;}
const imageOptions=[{value:'/images/form-dancing-building.webp',label:'Architecture · cool / geometric'},{value:'/images/serein-human.webp',label:'Retreat · warm / quiet'},{value:'/images/form-human.webp',label:'People · candid / documentary'}];
const tabs=['Style','Color','Type','Layout','Images'];
export function DesignLab(){
 const [style,setStyle]=useState(0),[d,setD]=useState<Design>({...presets[0].values}),[tab,setTab]=useState('Style'),[mobile,setMobile]=useState(false),[revision,setRevision]=useState(0);
 const [hue,setHue]=useState(225),[sat,setSat]=useState(65),[light,setLight]=useState(45),[harmony,setHarmony]=useState('complementary');
 const [title,setTitle]=useState('Go outside. Look a little closer.'),[body,setBody]=useState('A morning of architecture, observation, and sketching. Bring a notebook. Leave with a different way of seeing your city.'),[image,setImage]=useState(imageOptions[0].value),[uploaded,setUploaded]=useState(''),[alt,setAlt]=useState('Sculptural architecture with sweeping curved walls'),[error,setError]=useState(''),[notice,setNotice]=useState(''),[annotate,setAnnotate]=useState(false);
 const set=<K extends keyof Design>(key:K,value:Design[K])=>setD(prev=>({...prev,[key]:value}));
 function preset(i:number){setStyle(i);setD({...presets[i].values});setRevision(r=>r+1);setNotice(`${presets[i].name} applied. Your example text and image are kept.`);}
 const palette=harmony==='analogous'?[hsl((hue+330)%360,sat,light),hsl(hue,sat,light),hsl((hue+30)%360,sat,light)]:harmony==='triadic'?[hsl(hue,sat,light),hsl((hue+120)%360,sat,light),hsl((hue+240)%360,sat,light)]:harmony==='monochrome'?[hsl(hue,sat,25),hsl(hue,sat,50),hsl(hue,sat,85)]:[hsl(hue,sat,light),hsl((hue+180)%360,sat,light),hsl(hue,20,94)];
 const inkOnAccent=onColor(d.accent), heading=Math.round(d.size*d.scale**3),font=fonts[d.font as keyof typeof fonts];
 const checks=[{name:'Body / page',a:d.ink,b:d.bg,min:4.5},{name:'Body / card',a:d.ink,b:d.surface,min:4.5},{name:'Action text / fill',a:inkOnAccent,b:d.accent,min:4.5},{name:'Action fill / page',a:d.accent,b:d.bg,min:3}];
 const css=`/* Starting tokens, not a complete accessibility audit. */\n:root {\n  --background: ${d.bg};\n  --surface: ${d.surface};\n  --text: ${d.ink};\n  --accent: ${d.accent};\n  --on-accent: ${inkOnAccent};\n  --space: ${d.space/16}rem;\n  --radius: ${d.radius/16}rem;\n}\n.page {\n  background: var(--background);\n  color: var(--text);\n  font-family: ${font};\n  font-size: ${d.size/16}rem;\n  line-height: ${d.leading};\n  padding: var(--space);\n}\nh1 { font-size: clamp(1.5rem, 5vw, ${heading/16}rem); line-height: 1.12; }\n.card {\n  background: var(--surface);\n  border: ${style===1?'2':'1'}px solid var(--text);\n  border-radius: var(--radius);\n  box-shadow: ${style===1?'6px 6px 0 var(--text)':`0 ${Math.round(d.shadow/3)}px ${d.shadow}px #00000024`};\n}\n.action { background: var(--accent); color: var(--on-accent); min-height: 44px; }\n/* Load your chosen fonts; provide fallbacks. */`;
 async function copy(){try{await navigator.clipboard.writeText(css);setNotice('CSS copied.');}catch{setNotice('Copy unavailable. Select the CSS below and copy it manually.');}}
 function download(){const url=URL.createObjectURL(new Blob([css],{type:'text/css'}));const a=document.createElement('a');a.href=url;a.download='design-lab-tokens.css';a.click();URL.revokeObjectURL(url);setNotice('CSS downloaded.');}
 const sampleStyle={'--sample-bg':d.bg,'--sample-ink':d.ink,'--sample-accent':d.accent,'--sample-surface':d.surface,'--sample-on-accent':inkOnAccent,'--sample-font':font,'--sample-size':`${d.size/16}rem`,'--sample-heading':`${heading/16}rem`,'--sample-leading':d.leading,'--sample-space':`${d.space}px`,'--sample-radius':`${d.radius}px`,'--sample-shadow':style===1?'6px 6px 0 var(--sample-ink)':`0 ${Math.round(d.shadow/3)}px ${d.shadow}px #00000024`,'--sample-border':style===1?'2px':'1px'} as CSSProperties;
 return <main className="dl"><nav className="dl-nav"><a href={sitePath('/')}>← Portfolio</a><strong>DESIGN / LAB</strong><a href="#principles">The principles ↗</a></nav>
 <header className="dl-intro"><div><p className="dl-kicker">A working notebook for engineers</p><h1>Build an eye for design.</h1><p>Change a decision. See its effect. Learn why it works.</p></div><p className="dl-intro-note">Taste is judgment you can practice.<br/>Accessibility gives that judgment a foundation.</p></header>
 <div className="dl-workbench"><aside className="dl-controls"><Tabs value={tab} onValueChange={v=>setTab(String(v))}><TabsList aria-label="Design controls">{tabs.map(t=><TabsTrigger key={t} value={t}>{t}</TabsTrigger>)}</TabsList>
 <TabsContent value="Style"><h2>01 / Choose a direction</h2><p>Same content. Six different visual languages. Presets reset visual controls, so try one before fine-tuning.</p><div className="dl-presets">{presets.map((p,i)=><button key={p.name} aria-pressed={style===i} onClick={()=>preset(i)}><span style={{background:p.values.accent}}/>{p.name}</button>)}</div><div className="dl-note"><strong>{presets[style].note}</strong><p><b>Fits:</b> {presets[style].use}</p><p><b>Watch for:</b> {presets[style].avoid}</p></div><label className="dl-field">Example headline<input value={title} maxLength={100} onChange={e=>setTitle(e.target.value)}/></label><label className="dl-field">Example paragraph<textarea value={body} maxLength={450} rows={4} onChange={e=>setBody(e.target.value)}/></label></TabsContent>
 <TabsContent value="Color"><h2>02 / Color has a job</h2><p>Explore a relationship, then assign a swatch to the action accent. A pleasing palette can still fail contrast.</p><div className="dl-wheel" style={{'--angle':`${hue}deg`} as CSSProperties} aria-hidden="true"><span/><div>{hue}°<small>HUE</small></div></div><Range label="Hue" value={hue} min={0} max={359} unit="°" change={setHue}/><Range label="Saturation" value={sat} min={0} max={100} unit="%" change={setSat}/><Range label="Lightness" value={light} min={5} max={95} unit="%" change={setLight}/><Choice label="Color relationship" value={harmony} change={setHarmony} options={['complementary','analogous','triadic','monochrome'].map(value=>({value,label:value[0].toUpperCase()+value.slice(1)}))}/><div className="dl-swatches">{palette.map((c,i)=><button key={i} style={{background:c,color:onColor(c)}} aria-label={`Use ${c} as action accent`} onClick={()=>{set('accent',c);setRevision(r=>r+1);}}>{c}<small>Use accent</small></button>)}</div><h3>Or enter your own palette</h3><div className="dl-color-grid">{(['bg','surface','ink','accent'] as const).map((key,i)=><Color key={`${key}-${revision}`} label={['Page','Card','Text','Action'][i]} value={d[key]} change={v=>set(key,v)}/>)}</div><p className="dl-help">Action text automatically chooses the stronger of near-black and white. Other pairs remain yours to test.</p></TabsContent>
 <TabsContent value="Type"><h2>03 / Establish a hierarchy</h2><p>Make the reading order obvious before adding decoration.</p><Choice label="Font family" value={d.font} change={v=>set('font',v)} options={[{value:'sans',label:'Sans · Geist / Arial'},{value:'serif',label:'Serif · Georgia'},{value:'mono',label:'Mono · Geist Mono'}]}/><Range label="Body size" value={d.size} min={12} max={24} unit="px" change={v=>set('size',v)}/><Range label="Scale ratio" value={d.scale} min={1.1} max={1.5} step={.01} change={v=>set('scale',v)}/><Range label="Line height" value={d.leading} min={1.1} max={2} step={.05} change={v=>set('leading',v)}/><div className="dl-type-scale" style={{fontFamily:font}}><span style={{fontSize:Math.min(heading,44)}}>Aa / title</span><p>Base {d.size}px → section {Math.round(d.size*d.scale)}px → title {heading}px</p></div><div className="dl-note"><strong>A starting point, not a law.</strong><p>Try 16–18px body type and 1.5–1.8 line height. Small x-heights and dense paragraphs may need more space. Use relative units and test zoom.</p><p>{d.size<16?'Your body text is below the suggested starting range. Inspect it on a real phone.':'Your body size is in a useful reading range; context still matters.'}</p></div></TabsContent>
 <TabsContent value="Layout"><h2>04 / Make relationships visible</h2><p>Proximity groups related content. Alignment gives the eye a route through it.</p><Choice label="Image placement" value={d.layout} change={v=>set('layout',v)} options={[{value:'split',label:'Beside the text'},{value:'above',label:'Above the text'},{value:'below',label:'Below the text'}]}/><Range label="Spacing unit" value={d.space} min={8} max={48} unit="px" change={v=>set('space',v)}/><Range label="Corner radius" value={d.radius} min={0} max={32} unit="px" change={v=>set('radius',v)}/><Range label="Shadow blur" value={d.shadow} min={0} max={40} unit="px" change={v=>set('shadow',v)}/>{style===1&&<p className="dl-help">Neo-brutalist uses a fixed hard 6px shadow. Choose another style to explore soft blur.</p>}<div className="dl-note"><strong>One system, several distances.</strong><p>The preview uses your spacing unit for groups, half for related details, and twice for sections. Its columns stack when the preview is narrow.</p><p>Hover or keyboard-focus the action. Feedback should not depend on hover alone.</p></div></TabsContent>
 <TabsContent value="Images"><h2>05 / Art direction is selection</h2><p>Choose an image for its subject first, then its light, palette, and crop. A consistent filter cannot fix a mismatched subject.</p><Choice label="Example image" value={image} options={imageOptions} change={v=>{setImage(v);setUploaded('');setAlt(v===imageOptions[0].value?'Sculptural architecture with sweeping curved walls':v===imageOptions[1].value?'A person resting in a quiet retreat':'People spending time together');}}/><label className="dl-field">Try your own image<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const f=e.target.files?.[0];setError('');if(!f)return;if(!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>5*1024*1024){setError('Choose a JPG, PNG, or WebP smaller than 5 MB.');return;}const reader=new FileReader();reader.onload=()=>{setUploaded(String(reader.result));setAlt('');};reader.onerror=()=>setError('This file could not be read. Try another image.');reader.readAsDataURL(f);}}/></label><p className="dl-help">Previewed only in this tab. Nothing is uploaded or saved.</p>{error&&<p role="alert">{error}</p>}<label className="dl-field">Image description (alt text)<textarea rows={2} value={alt} maxLength={250} onChange={e=>setAlt(e.target.value)}/></label>{uploaded&&!alt&&<p className="dl-help">Empty alt text marks the image as decorative. Add a description if it carries meaning.</p>}<Range label="Horizontal focal point" value={d.crop} min={0} max={100} unit="%" change={v=>set('crop',v)}/><div className="dl-note"><strong>Compare before you commit.</strong><p>The warm retreat photo changes the mood, but does it explain an architecture walk? Relevance beats matching colors. Check the narrow preview before choosing a crop.</p></div></TabsContent>
 </Tabs></aside>
 <section className="dl-preview" aria-label="Live design example"><div className="dl-preview-bar"><span>LIVE EXAMPLE <b>{presets[style].name}</b></span><div><button aria-pressed={!mobile} onClick={()=>setMobile(false)}>Wide</button><button aria-pressed={mobile} onClick={()=>setMobile(true)}>Narrow</button><button aria-pressed={annotate} onClick={()=>setAnnotate(!annotate)}>Explain</button></div></div><div className={`dl-canvas ${mobile?'is-narrow':''}`}><article className={`dl-sample ${annotate?'is-annotated':''}`} style={sampleStyle}><div className="dl-sample-nav"><strong>fieldnotes.</strong><span>Walks & observations</span></div><div className={`dl-sample-hero image-${d.layout}`}><div className="dl-sample-copy"><span className="dl-sample-eyebrow">SATURDAY SERIES / 01</span><h2>{title||'Your headline'}</h2><p>{body||'Your description'}</p><button className="dl-sample-action" onClick={()=>setNotice('Example action activated. In a real product, this would open the reservation flow.')}>Reserve a place <span aria-hidden="true">↗</span></button>{annotate&&<small className="dl-annotation">One clear action. The headline leads; the paragraph supports it.</small>}</div><figure><img src={uploaded||sitePath(image)} alt={alt} style={{objectPosition:`${d.crop}% center`}} onError={()=>setError('The image could not be displayed. Choose a different file or example.')}/><figcaption>Look at the city with fresh eyes.</figcaption>{annotate&&<small className="dl-annotation">The crop protects the subject at each width.</small>}</figure></div><div className="dl-sample-cards"><section><span>01 / OBSERVE</span><h3>Notice the details.</h3><p>Look for rhythm, scale, and the space between things.</p></section><section><span>02 / SHARE</span><h3>Compare what you saw.</h3><p>Two people can walk the same street and see different things.</p></section></div>{annotate&&<small className="dl-annotation">Related content shares a surface and consistent spacing.</small>}</article></div><p className="dl-preview-caption">Experimental canvas: your values can intentionally produce inaccessible combinations. The controls stay readable.</p>
 <section className="dl-contrast" aria-label="Live contrast checks"><header><h3>Measure what you can.</h3><span>WCAG 2.2 / AA thresholds</span></header><div>{checks.map(c=>{const ratio=contrast(c.a,c.b),pass=ratio>=c.min;return <article key={c.name}><span>{c.name}</span><strong>{ratio.toFixed(2)}<small>:1</small></strong><p className={pass?'dl-pass':'dl-fail'}>{pass?'✓ Meets':'! Below'} {c.min}:1</p></article>;})}</div><p>Text checks use the stricter ordinary-text threshold. Action fill checks separation from the page, not full control conformance. Ratios are evaluated before rounding. Images, focus, zoom, and other states need separate checks.</p></section></section></div>
 <div className="dl-status" role="status" aria-live="polite">{notice}</div>
 <section className="dl-principles" id="principles"><header><p className="dl-kicker">From experimentation to judgment</p><h2>The reasons behind the controls.</h2><p>Use these as short studio exercises. Change one variable at a time and explain the tradeoff to someone else.</p></header><div>{lessons.map((l,i)=><article key={l.title}><span className="dl-lesson-number">0{i+1}</span><div><h3>{l.title}</h3><p>{l.body}</p><p className="dl-exercise"><b>Try it:</b> {l.task}</p></div></article>)}</div></section>
 <section className="dl-export"><div><p className="dl-kicker">Take the experiment into code</p><h2>Your values, as CSS.</h2><p>These are starting tokens for your project. Add responsive rules, real content, and test every interaction. Changes are temporary until you export.</p><button onClick={copy}>Copy CSS</button><button onClick={download}>Download CSS</button><button onClick={()=>preset(style)}>Reset visual controls</button></div><pre tabIndex={0} aria-label="Generated CSS"><code>{css}</code></pre></section>
 <footer className="dl-footer"><p><strong>Keep learning from the source.</strong> This lab teaches selected checks; it does not certify WCAG conformance.</p><div><a href="https://www.w3.org/WAI/WCAG22/Understanding/contrast-minimum.html">Text contrast ↗</a><a href="https://www.w3.org/WAI/WCAG22/Understanding/non-text-contrast.html">Non-text contrast ↗</a><a href="https://www.w3.org/WAI/WCAG22/Understanding/target-size-minimum.html">Target sizes ↗</a><a href="https://www.w3.org/WAI/tutorials/images/">Image alternatives ↗</a><a href={sitePath('/')}>Back to the portfolio</a></div></footer></main>;
}
