export const imageSets = [
 {name:'Minimal / form & space',note:'Quiet backgrounds, clear silhouettes, and room around the subject.',images:[['form-kinetic-chair.webp','A sculptural chair','Shape'],['form-soft-architecture.webp','Soft architectural forms','Space'],['form-chair-detail.webp','A close view of a chair','Detail']]},
 {name:'Neo-brutalist / material & movement',note:'Strong subjects, direct crops, and tactile materials suit hard frames.',images:[['vernacular-plates-hero.jpg','Stacked sculptural paper plates','Material'],['form-dancing-building.webp','A dancer between concrete walls','Movement'],['vernacular-plates-detail.jpg','A close view of paper plate texture','Texture']]},
 {name:'Editorial / people & process',note:'An establishing portrait, an action, and a detail tell a small story.',images:[['form-useful-accident.webp','People working together in a studio','The people'],['form-studio-detail.webp','A studio detail','The process'],['form-accident-detail.webp','A close view from the studio','The detail']]},
 {name:'Swiss / structure & rhythm',note:'Architectural lines and object studies support a precise grid.',images:[['form-dancing-building.webp','A dancer between concrete walls','Structure'],['form-building-detail.webp','An architectural detail','Rhythm'],['form-kinetic-chair.webp','A sculptural chair','Proportion']]},
 {name:'Night mode / blue hour',note:'A consistent low-light setting gives the series a shared atmosphere.',images:[['serein-dusk.webp','A retreat at dusk','Dusk'],['serein-dusk-v2.webp','Another view of the retreat at dusk','Blue hour'],['serein-residence-onsen.webp','A quiet bathing space','Stillness']]},
 {name:'Playful / illustrated food',note:'Illustration adds warmth; keep the drawing language consistent across the set.',images:[['pantry-sketch-hero.jpg','An illustrated food composition','Gather'],['pantry-tomato-sketch.jpg','An illustration of tomatoes','Color'],['pantry-galette-sketch.jpg','An illustrated galette','Share']]},
 {name:'Cinema / cast & atmosphere',note:'Fictional cast artwork from MERIDIAN: a lead portrait and supporting characters.',images:[['meridian-mira-ellery.png','Fictional character Ada Vale in cinematic artwork','The lead'],['meridian-jonah-reed.png','Fictional conductor in cinematic artwork','The conductor'],['meridian-ines-calder.png','Fictional signal engineer in cinematic artwork','The engineer']]},
 {name:'Terminal / field documentation',note:'Functional views of objects and spaces; desaturation creates a document-like treatment.',images:[['form-building-detail.webp','An architectural detail','Record 001'],['form-chair-detail.webp','A close view of a chair','Record 002'],['form-soft-detail.webp','A close view of architectural forms','Record 003']]},
 {name:'Bento / fashion in motion',note:'Mix a wider scene with closer garment studies to give each tile a purpose.',images:[['atelier-motion-hero.jpg','Fashion photographed in motion','Movement'],['atelier-orbit-jacket.jpg','A sculptural jacket','Silhouette'],['atelier-bias-drape.jpg','A draped garment','Drape']]},
 {name:'Quiet luxury / a place to pause',note:'Warm light, natural materials, and a wide-to-close sequence create continuity.',images:[['serein-residence-suite.webp','A quiet guest suite','Stay'],['serein-residence-table.webp','A table set for a meal','Gather'],['serein-onsen-detail.webp','A detail of a bathing space','Unwind']]},
];
