export type Design = { bg:string; ink:string; accent:string; surface:string; font:string; size:number; scale:number; leading:number; space:number; radius:number; shadow:number; layout:string; crop:number };
export const fonts = { sans:'var(--font-geist-sans, Arial), Arial, sans-serif', serif:'Georgia, "Times New Roman", serif', mono:'var(--font-geist-mono, monospace), monospace' };
export const presets: {name:string; note:string; use:string; avoid:string; values:Design}[] = [
 {name:'Minimal',note:'Less competition. More hierarchy.',use:'Documentation, tools, and focused product pages.',avoid:'Removing labels or boundaries people need.',values:{bg:'#f5f6f8',ink:'#172029',accent:'#254edb',surface:'#ffffff',font:'sans',size:16,scale:1.25,leading:1.65,space:28,radius:10,shadow:12,layout:'split',crop:50}},
 {name:'Neo-brutalist',note:'Hard edges. Unapologetic emphasis.',use:'Independent brands, events, and playful experiments.',avoid:'Making every element shout at the same volume.',values:{bg:'#fff7df',ink:'#171717',accent:'#f6d447',surface:'#ffffff',font:'sans',size:17,scale:1.33,leading:1.55,space:24,radius:0,shadow:0,layout:'split',crop:50}},
 {name:'Editorial',note:'Type sets the rhythm.',use:'Stories, culture, portfolios, and long-form reading.',avoid:'Tiny captions and excessively thin type.',values:{bg:'#f4eee6',ink:'#30221e',accent:'#883b26',surface:'#fffaf3',font:'serif',size:18,scale:1.33,leading:1.75,space:32,radius:0,shadow:0,layout:'above',crop:50}},
 {name:'Swiss',note:'A grid, a clear order, one strong accent.',use:'Information-rich pages and public communication.',avoid:'Treating strict alignment as a substitute for clear content.',values:{bg:'#ffffff',ink:'#161616',accent:'#bb211e',surface:'#f0f0f0',font:'sans',size:16,scale:1.4,leading:1.6,space:24,radius:0,shadow:0,layout:'split',crop:50}},
 {name:'Night mode',note:'Depth without glare.',use:'Media, creative software, and evening reading.',avoid:'Pure-white walls of text and invisible dark borders.',values:{bg:'#111827',ink:'#e8edf6',accent:'#a9bfff',surface:'#202c40',font:'sans',size:17,scale:1.25,leading:1.7,space:28,radius:16,shadow:16,layout:'split',crop:50}},
 {name:'Playful',note:'Rounded forms with a disciplined system.',use:'Learning, community, and friendly consumer products.',avoid:'Using a friendly style to hide important consequences.',values:{bg:'#ecf7f4',ink:'#163f39',accent:'#7028ad',surface:'#ffffff',font:'sans',size:17,scale:1.25,leading:1.65,space:24,radius:28,shadow:20,layout:'above',crop:50}},
];
export function luminance(hex:string){const rgb=hex.slice(1).match(/../g)!.map(c=>parseInt(c,16)/255).map(c=>c<=.04045?c/12.92:((c+.055)/1.055)**2.4);return .2126*rgb[0]+.7152*rgb[1]+.0722*rgb[2];}
export function contrast(a:string,b:string){const x=luminance(a),y=luminance(b);return(Math.max(x,y)+.05)/(Math.min(x,y)+.05);}
export function onColor(bg:string){return contrast(bg,'#ffffff')>=contrast(bg,'#111111')?'#ffffff':'#111111';}
export function hsl(h:number,s:number,l:number){s/=100;l/=100;const a=s*Math.min(l,1-l),f=(n:number)=>{const k=(n+h/30)%12;return l-a*Math.max(-1,Math.min(k-3,9-k,1));};return '#'+[f(0),f(8),f(4)].map(x=>Math.round(x*255).toString(16).padStart(2,'0')).join('');}
export const lessons = [
 {title:'Start with the job, then choose the mood.',body:'Write who the page serves, what they need to do, and three useful qualities: for example, “clear, dependable, quick” for a student timetable. Pick a style that supports those qualities. A visual trend is a tool, not a requirement.',task:'Compare Minimal and Neo-brutalist. Which helps you find the next action faster? What would change for a music festival?'},
 {title:'Color is a relationship, not a personality test.',body:'Hue is the color family; saturation is its intensity; lightness is how light or dark it appears. The wheel uses HSL, which is intuitive but not perceptually uniform. Equal numerical steps do not always look equal. Analogous hues sit nearby; complementary hues oppose one another. Neither arrangement guarantees readable contrast.',task:'Keep hue fixed and change lightness. Watch the contrast checks. Then try the same accent on a light and a dark surface.'},
 {title:'Give every color a job.',body:'Use a background, a surface, readable text, and an action accent. Repeating these roles makes the interface easier to learn. A dominant neutral with a smaller accent is a useful starting point, not a mandatory percentage. Reserve error and success meaning for labeled feedback; never rely on red versus green alone.',task:'Make the button the strongest accent. If everything is an accent, what should someone notice first?'},
 {title:'Size establishes order; spacing establishes groups.',body:'A modular type scale multiplies a base size to create related heading sizes. Start near 16–18px for body text, then judge the actual font and reading distance. These are practical starting points, not WCAG minimum font sizes. Try line-height around 1.5–1.8 and a readable measure near 45–75 characters. Keep related items closer than unrelated sections.',task:'Set spacing to 8, then 40. Find the point where groups become clear without disconnecting the heading from its paragraph.'},
 {title:'Choose images that carry information.',body:'Match subject, lighting, color temperature, and crop across a set. Leave space around the subject and inspect mobile crops. A photo of a real activity can explain more than a generic mood image. Color harmony cannot rescue an irrelevant image. Use images you have rights to use and describe meaningful content in alt text; use empty alt text only for decoration.',task:'Try a wide crop, then a narrow preview. Move the focal point until the important subject survives both. Write alt text describing what matters here.'},
 {title:'Depth should explain interaction.',body:'Shadows can separate a raised card from its background; a harder offset communicates a different character from a soft blur. Hover is an enhancement: touch and keyboard users still need labels, visible boundaries, and focus. Avoid moving whole layouts on hover, and respect reduced-motion preferences.',task:'Tab to the preview action. Compare its focus treatment with hover. Can you still identify the action without a mouse?'},
 {title:'Accessibility is more than passing one ratio.',body:'For WCAG 2.2 AA, ordinary text needs 4.5:1 contrast; large text needs 3:1 (at least 24 CSS px regular or about 18.67px bold). Essential control boundaries and graphics generally need 3:1 against adjacent colors. These checks cover only the listed solid-color pairs, not photographs, every state, or full conformance.',task:'Also test keyboard order, zoom to 200%, narrow layouts, meaningful labels, and reduced motion. Pointer targets need 24×24 CSS px at AA with exceptions; 44×44 is a comfortable design target.'},
];
