export const meridianCast = [
  { slug: 'mira-ellery', first: 'Mira', last: 'Ellery', role: 'Ada Vale', credit: 'THE NIGHT OPERATOR', line: 'Her brother has been missing for twenty years.', description: 'At 11:48 p.m., Ada hears three knocks over the station radio—the signal her brother Tom used to make through their bedroom wall. Then his voice: “Platform four. Don’t let them close it.” The transmission is coming from Car 07, which vanished inside Meridian Tunnel when Ada was nine.', note: 'The city is sealing the tunnel at midnight. Ada has twelve minutes to reach the old platform. She takes a portable receiver and the passenger list she has spent twenty years being told does not exist.' },
  { slug: 'jonah-reed', first: 'Jonah', last: 'Reed', role: 'Elias Rook', credit: 'THE CONDUCTOR', line: 'He signed the empty-car report.', description: 'Rook was driving Car 07 the night it disappeared. He escaped through a maintenance shaft and told the inquiry he had finished his last run. No passengers. No one to search for. He has collected a railway pension ever since.', note: 'Ada finds him waiting at the sealed station in his old uniform, holding thirteen unused tickets. He knows a way down. Before he will take her, he asks her to turn off the recorder.' },
  { slug: 'ines-calder', first: 'Ines', last: 'Calder', role: 'Mara Voss', credit: 'THE SIGNAL ENGINEER', line: 'She kept the order. And the name on it.', description: 'Mara changed the points that sent Car 07 into the closed tunnel. At the inquiry, she said the signal had failed. In a biscuit tin beneath her sink, she kept the written order to divert the tram, complete with the signature the railway asked her to tear off.', note: 'Now that same signature is on the order to seal the tunnel. Mara can stop the work from the old signal cabin, but restoring its power will also set Car 07 moving. She needs Ada to find the passengers before she throws the switch.' },
] as const;

export const meridianSynopsis = 'At 11:48 p.m., a tram missing for twenty years calls the station. Ada Vale recognizes her brother’s voice among the passengers. At midnight, the city will seal the tunnel for good. To reach him, she needs the conductor who swore the car was empty—and the engineer who knows why it was sent underground.';

export const meridianScreenings = [
  { city: 'London', venue: 'The Lantern Cinema', district: 'Riverside', format: '35mm concept screening', times: ['Friday · 7:30 PM', 'Saturday · 9:00 PM'] },
  { city: 'New York', venue: 'Meridian Film House', district: 'Lower Manhattan', format: 'Midnight double-bill concept', times: ['Friday · 11:45 PM', 'Saturday · 11:45 PM'] },
  { city: 'Los Angeles', venue: 'The Afterlight', district: 'Eastside', format: 'Director’s edition concept', times: ['Friday · 8:00 PM', 'Sunday · 6:00 PM'] },
] as const;
