export const identities: Record<string, { name: string; idea: string; voice: string; signature: string }> = {
  nova: { name: 'The focal point', idea: 'Four data tiles converge on one clear decision. The open center is the attention NOVA gives back.', voice: 'Precise, composed, actionable.', signature: 'A square grid, a single lime accent, and compact numerical typography.' },
  serein: { name: "The residence seal", idea: "A fine oval encloses a drawn S, with a small diamond above it. The proportion recalls a hotel seal: poised, personal, and quietly ceremonial.", voice: "Unhurried, warm, observant.", signature: "Cedar tones, a fine monogram, continuous dawn and dusk photography, and a spacious editorial serif." },
  form: { name: 'The movable specimen', idea: 'Three unequal pieces assemble an F. Each piece has its own scale, just like the objects, people, and ideas in the archive.', voice: 'Curious, direct, independent.', signature: 'Poster typography, deliberate collisions, and an expressive modular grid.' },
  aura: { name: "The light opening", idea: "A soft arch opens into a single flowing line. It suggests light gathering at an edge, without extra punctuation in the wordmark.", voice: "Gentle, spacious, emotionally specific.", signature: "Frosted glass, slowly drifting lavender and orange light, and precise player controls." },
  vernacular: { name: "The folded V", idea: "One bold V turns back on itself like a scored sheet. The compact silhouette comes from paper structure and survives at label size.", voice: "Blunt, tactile, materially honest.", signature: "A folded initial, yellow and cobalt, tactile product photographs, and oversized type." },
  field: { name: "The trail initial", idea: "A sturdy F carries a small summit at its foot. Direction and terrain are reduced to two immediately legible forms.", voice: "Plain, practical, attentive.", signature: "A practical initial, map geometry, trail colors, and clear route facts." },
  atelier: { name: "The tailored monogram", idea: "An A and a fine central T share an axis. Hairline terminals and deliberate proportions reference a garment label rather than a software icon.", voice: "Restrained, exacting, reflective.", signature: "A fine monogram, modern sans-serif editorial type, and overlapping garment compositions." },
  signal: { name: 'The measured step', idea: 'Three measured levels end at a clear point. It is a record of changing values, with each step connected to the last.', voice: 'Reassuring, transparent, concrete.', signature: 'Warm dark surfaces, tabular figures, and trend color paired with plain language.' },
  civic: { name: "The public hall", idea: "Three open columns support a common roof. It reads as a shared civic place and stays distinct from NOVA's data tiles.", voice: "Public, plainspoken, accountable.", signature: "An architectural silhouette, municipal blue, ruled records, and plain language." },
  lumen: { name: 'The shared table', idea: 'Three cards gather around an open tabletop. The mark starts with the human act of planning together.', voice: 'Simple, candid, grounded.', signature: 'Paper cards, graphite rules, and three honest horizons: Now, Next, Later.' },
  pantry: { name: "The everyday sketch", idea: "SCRIBBLE takes its name from the first mark on a shopping list. The loosely drawn bowl and leaf make the food identity informal and recognisable.", voice: "Appetizing, friendly, informal.", signature: "Marker drawings, ingredient colors, handwritten accents, and recipe-like product information." },
};
